/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stackinfix;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author MILAN PATEL
 */
public class home extends javax.swing.JFrame {

    Stack stack;
    static int top = 0;
    Object sp;
    Image img;
    Conversion c;

    public home() {

        this.stack = new Stack();
        initComponents();
        //this.setLayout(new BorderLayout());
        //this.setLayout(new FlowLayout());
        img = Toolkit.getDefaultToolkit().getImage("icon1.png");
        this.setIconImage(img);
        this.setLayout(null);
        footerLabel.setText("\u00A9" + " Charusat University");

    }

    /**
     * Creates new form home
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastPop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infixtopostfixPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        infixTextBox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        infixButton = new javax.swing.JButton();
        postfixTextBox = new javax.swing.JTextField();
        prefixTextBox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        postfixButton = new javax.swing.JButton();
        prefixButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        footerLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stackPanel = new javax.swing.JPanel();
        s5 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s0 = new javax.swing.JLabel();
        pushTextBox = new javax.swing.JTextField();
        pushButton = new javax.swing.JButton();
        popButton = new javax.swing.JButton();
        topPointerPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        topPointerLabel = new javax.swing.JLabel();
        lastpopPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lastPopLabel = new javax.swing.JLabel();
        resetButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        lastPop.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lastPop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stack");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stack || Infix-Postfix-Prefix");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(800, 600));

        infixtopostfixPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        infixtopostfixPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Papyrus", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Converter");
        infixtopostfixPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 199, 33));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Infix:");
        infixtopostfixPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, -1));

        infixTextBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        infixTextBox.setToolTipText("");
        infixtopostfixPanel.add(infixTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 297, 29));
        infixTextBox.getAccessibleContext().setAccessibleName("infixtb");

        jLabel15.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Postfix:");
        infixtopostfixPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));

        infixButton.setText("Convert");
        infixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infixButtonActionPerformed(evt);
            }
        });
        infixtopostfixPanel.add(infixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));
        infixButton.getAccessibleContext().setAccessibleName("convertbtn");

        infixtopostfixPanel.add(postfixTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 297, 30));
        postfixTextBox.getAccessibleContext().setAccessibleName("posttb");

        infixtopostfixPanel.add(prefixTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 297, 30));

        jLabel17.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Prefix:");
        infixtopostfixPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, -1));

        postfixButton.setText("Convert");
        postfixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postfixButtonActionPerformed(evt);
            }
        });
        infixtopostfixPanel.add(postfixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        prefixButton.setText("Convert");
        prefixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefixButtonActionPerformed(evt);
            }
        });
        infixtopostfixPanel.add(prefixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        resetButton.setBackground(new java.awt.Color(204, 0, 0));
        resetButton.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        infixtopostfixPanel.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Infix <=> Postfix <=> Prefix");
        infixtopostfixPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 250, 33));

        footerLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        footerLabel.setText("  ");
        infixtopostfixPanel.add(footerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 130, -1));

        jLabel6.setText("Milan Patel(16IT083)");
        infixtopostfixPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 130, -1));

        stackPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        s5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s5.setAlignmentY(0.0F);
        s5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackPanel.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 42, 56, 30));

        s4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        s4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s4.setAlignmentY(0.0F);
        s4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackPanel.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 78, 56, 30));

        s2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        s2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s2.setAlignmentY(0.0F);
        s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackPanel.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 148, 56, 30));

        s3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        s3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s3.setAlignmentY(0.0F);
        s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackPanel.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 112, 56, 30));

        s1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s1.setAlignmentY(0.0F);
        s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackPanel.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 184, 56, 30));

        s0.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        s0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s0.setAlignmentY(0.0F);
        s0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stackPanel.add(s0, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 220, 56, 30));

        pushTextBox.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        pushTextBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pushTextBox.setPreferredSize(new java.awt.Dimension(6, 25));
        pushTextBox.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pushTextBoxInputMethodTextChanged(evt);
            }
        });
        pushTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushTextBoxActionPerformed(evt);
            }
        });
        stackPanel.add(pushTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, 34));
        pushTextBox.getAccessibleContext().setAccessibleName("pushtb");

        pushButton.setBackground(new java.awt.Color(153, 153, 153));
        pushButton.setText("PUSH");
        pushButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushButtonActionPerformed(evt);
            }
        });
        stackPanel.add(pushButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 30));
        pushButton.getAccessibleContext().setAccessibleName("pushbtn");

        popButton.setText("POP");
        popButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popButtonActionPerformed(evt);
            }
        });
        stackPanel.add(popButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 60, -1));
        popButton.getAccessibleContext().setAccessibleName("popbtn");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Top Pointer");

        topPointerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        topPointerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topPointerLabel.setText("-1");
        topPointerLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout topPointerPanelLayout = new javax.swing.GroupLayout(topPointerPanel);
        topPointerPanel.setLayout(topPointerPanelLayout);
        topPointerPanelLayout.setHorizontalGroup(
            topPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPointerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPointerPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(topPointerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap())
        );
        topPointerPanelLayout.setVerticalGroup(
            topPointerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPointerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topPointerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        stackPanel.add(topPointerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 112, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Last POP");

        lastPopLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastPopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastPopLabel.setText("     ");
        lastPopLabel.setToolTipText("");
        lastPopLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout lastpopPanelLayout = new javax.swing.GroupLayout(lastpopPanel);
        lastpopPanel.setLayout(lastpopPanelLayout);
        lastpopPanelLayout.setHorizontalGroup(
            lastpopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastpopPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(lastpopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastPopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lastpopPanelLayout.setVerticalGroup(
            lastpopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastpopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastPopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        stackPanel.add(lastpopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        resetButton1.setBackground(new java.awt.Color(204, 0, 0));
        resetButton1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        resetButton1.setText("RESET");
        resetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton1ActionPerformed(evt);
            }
        });
        stackPanel.add(resetButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Stack");
        stackPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(infixtopostfixPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infixtopostfixPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popButtonActionPerformed
        //pop
        if (stack.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Stack Is Underflow.");
        } else {
            if (top == 1) {
                top--;
                s0.setText(null);
                sp = stack.pop();
                lastPop(sp);
            } else if (top == 2) {
                top--;
                s1.setText(null);
                sp = stack.pop();
                lastPop(sp);
            } else if (top == 3) {
                top--;
                s2.setText(null);
                sp = stack.pop();
                lastPop(sp);
            } else if (top == 4) {
                top--;
                s3.setText(null);
                sp = stack.pop();
                lastPop(sp);
            } else if (top == 5) {
                top--;
                s4.setText(null);
                sp = stack.pop();
                lastPop(sp);
            } else if (top == 6) {
                top--;
                s5.setText(null);
                sp = stack.pop();
                lastPop(sp);
            }
        }
        topP(top - 1);
    }//GEN-LAST:event_popButtonActionPerformed

    private void pushButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushButtonActionPerformed
        //push
        String s = pushTextBox.getText();
        if (top == 6) {

            JOptionPane.showMessageDialog(this, "Stack Is Overflow.");
        } else if (s.length() == 0) {
            JOptionPane.showMessageDialog(this, "Please, Enter Value.");
        
        }else{
            if(Character.isDigit(s.charAt(0)) || StackInfix.isOperator(s.charAt(0))|| (!(s.length()>1) && !Character.isDigit(s.charAt(0)))){

                if (top == 6) {

                    JOptionPane.showMessageDialog(this, "Stack Is Overflow.");
                } else if (top == 0) {
                    s0.setText(s);
                    stack.push(s);
                    top++;
                } else if (top == 1) {
                    s1.setText(s);
                    stack.push(s);
                    top++;
                } else if (top == 2) {
                    s2.setText(s);
                    stack.push(s);
                    top++;
                } else if (top == 3) {
                    s3.setText(s);
                    stack.push(s);
                    top++;
                } else if (top == 4) {
                    s4.setText(s);
                    stack.push(s);
                    top++;
                } else if (top == 5) {
                    s5.setText(s);
                    stack.push(s);
                    top++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "Please, Enter Value.");
            }
        }
        pushTextBox.setText(null);
        topP(top - 1);
    }//GEN-LAST:event_pushButtonActionPerformed

    private void pushTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pushTextBoxActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        //reset
        top=0;
        postfixTextBox.setText(null);
        infixTextBox.setText(null);
        prefixTextBox.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void prefixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefixButtonActionPerformed
        //prefix
        String get = prefixTextBox.getText();
        if (get.length() == 0) {

            JOptionPane.showMessageDialog(this, "Please, Enter Vailid Input.");
        } else {

            String putPost = Conversion.prefixToPostfix(get);
            String putIn = Conversion.postfixToInfix(putPost);
            postfixTextBox.setText(putPost);
            infixTextBox.setText(putIn);
        }
    }//GEN-LAST:event_prefixButtonActionPerformed

    private void postfixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postfixButtonActionPerformed
        //post
        String get = postfixTextBox.getText();
        if (get.length() == 0) {

            JOptionPane.showMessageDialog(this, "Please, Enter Vailid Input.");
        } else {

            String putIn = Conversion.postfixToInfix(get);
            String putPre = Conversion.infixToPrefix(putIn);
            infixTextBox.setText(putIn);
            prefixTextBox.setText(putPre);
        }
    }//GEN-LAST:event_postfixButtonActionPerformed

    private void infixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infixButtonActionPerformed
        //infix
        String get = infixTextBox.getText();
        if (get.length() == 0) {

            JOptionPane.showMessageDialog(this, "Please, Enter Vailid Input.");
        } else {

            String putPost = Conversion.infixToPostfix(get);
            String putPre = Conversion.infixToPrefix(get);
            postfixTextBox.setText(putPost);
            prefixTextBox.setText(putPre);
        }
    }//GEN-LAST:event_infixButtonActionPerformed

    private void pushTextBoxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pushTextBoxInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pushTextBoxInputMethodTextChanged

    private void resetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton1ActionPerformed

        lastPopLabel.setText("   ");
        s0.setText(null);
        s1.setText(null);
        s2.setText(null);
        s3.setText(null);
        s4.setText(null);
        s5.setText(null);
        topPointerLabel.setText("-1");
    }//GEN-LAST:event_resetButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        home h1;
        h1 = new home();
        h1.setVisible(true);
    }

    //function
    void lastPop(Object ob) {
        lastPopLabel.setText(ob.toString());
    }

    void topP(int n) {
        Integer i = n;
        topPointerLabel.setText(i.toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footerLabel;
    private javax.swing.JButton infixButton;
    private javax.swing.JTextField infixTextBox;
    private javax.swing.JPanel infixtopostfixPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastPop;
    private javax.swing.JLabel lastPopLabel;
    private javax.swing.JPanel lastpopPanel;
    private javax.swing.JButton popButton;
    private javax.swing.JButton postfixButton;
    private javax.swing.JTextField postfixTextBox;
    private javax.swing.JButton prefixButton;
    private javax.swing.JTextField prefixTextBox;
    private javax.swing.JButton pushButton;
    private javax.swing.JTextField pushTextBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton1;
    private javax.swing.JLabel s0;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JPanel stackPanel;
    private javax.swing.JLabel topPointerLabel;
    private javax.swing.JPanel topPointerPanel;
    // End of variables declaration//GEN-END:variables

    private String String(Object ob) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
